[package]
name = "confit-core"
version = "0.6.1"
edition = "2024"

[lints]
workspace = true

[dependencies]
chrono = "0.4.45"
crossbeam-channel = "0.5.17"
diffy = "0.5.2"
dirs = "7.0.0"
flate2 = "1.1.10"
log = "0.4"
noyalib.workspace = true
rayon = "1.12"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar = "0.4.46"
thiserror.workspace = true
toml.workspace = true
