[package]
name = "confit-store"
version = "0.8.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
confit-core = { version = "0.8.0", path = "../core" }
flate2 = "1.1.10"
serde_json.workspace = true
sha2 = "0.11.0"
tar = "0.4.46"
ureq = "3.4.2"

[dev-dependencies]
tempfile.workspace = true
