[package]
name = "confit-store"
version = "0.8.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
confit-model = { version = "0.8.0", path = "../model" }
confit-driver = { version = "0.8.0", path = "../driver" }
dirs = "7.0.0"
flate2 = "1.1.10"
serde_json.workspace = true
sha2 = "0.11.0"
tar = "0.4.46"
ureq = "3.4.2"
zip = "8.6.0"

[dev-dependencies]
confit-driver = { path = "../driver", features = ["test-support"] }
crossbeam-channel = "0.5.17"
tempfile.workspace = true
